[theme]
primaryColor = "#62DCFF"
backgroundColor = "#05070D"
secondaryBackgroundColor = "#0B1C2D"
textColor = "#F7FBFF"
font = "sans serif"

[server]
maxUploadSize = 200
maxMessageSize = 200
headless = true
enableCORS = true
enableXsrfProtection = true
enableWebsocketCompression = true

[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
