[theme]
primaryColor = "#62DCFF"
backgroundColor = "#05070D"
secondaryBackgroundColor = "#0B1C2D"
textColor = "#F7FBFF"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true

[browser]
gatherUsageStats = false
